In [2]:
# Regresión Lineal Simple

# Cómo importar las librerías
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import valohai
import os 
import json
import warnings
warnings.filterwarnings("ignore")

#dataset = pd.read_csv('Salary_Data.csv')

#Get the path to the folder where Valohai inputs are
input_path = os.getenv('VH_INPUTS_DIR', '.inputs/')
# Get the file path of our MNIST dataset that we defined in our YAML
dataset_path = os.path.join(input_path, 'salary_yaml/Salary_Data.csv')
dataset = pd.read_csv(dataset_path)
#X = dataset.iloc[:, :-1].values
#y = dataset.iloc[:, 1].values
X = dataset.drop("Salary",axis=1)
y = dataset["Salary"]

# Dividir el data set en conjunto de entrenamiento y conjunto de testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/3, random_state = 0)

output_path = os.getenv('VH_OUTPUTS_DIR', '.outputs/')
OutDataset = os.path.join(output_path, 'train_dataframe.csv')

X_train["Salary"]=y_train.tolist()
train = X_train
#train.to_csv ("train_dataframe.csv", index = False, header=True)
train.to_csv (OutDataset, index = False, header=True)

OutDataset2 = os.path.join(output_path, 'test_dataframe.csv')
X_test["Salary"]=y_test.tolist()
test = X_test
test.to_csv (OutDataset2, index = False, header=True)


In [4]:
#OBTENCIÓN DE TRAIN Y TEST DESDE VALOHAI A TRAVÉS DE ARCHIVO YAML

#Get the path to the folder where Valohai inputs are
input_path = os.getenv('VH_INPUTS_DIR', '.inputs/')
# Get the file path of our MNIST dataset that we defined in our YAML
dataset_train_path = os.path.join(input_path, 'train_yaml/train_dataframe.csv')

#Get the path to the folder where Valohai inputs are
input_path = os.getenv('VH_INPUTS_DIR', '.inputs/')
# Get the file path of our MNIST dataset that we defined in our YAML
dataset_test_path = os.path.join(input_path, 'test_yaml/test_dataframe.csv')


dataset_train = pd.read_csv(dataset_train_path)
#dataset_train= dataset_train.rename(columns={'YearsExperience':'X_train',
#                                   'Salary':'y_train'})
X_train = dataset_train.iloc[:, :-1].values
y_train = dataset_train.iloc[:, 1].values

dataset_test = pd.read_csv(dataset_train_path)
#dataset_train= dataset_train.rename(columns={'YearsExperience':'X_train',
#                                   'Salary':'y_train'})
X_test = dataset_test.iloc[:, :-1].values
y_test = dataset_test.iloc[:, 1].values

# Crear modelo de Regresión Lienal Simple con el conjunto de entrenamiento
from sklearn.linear_model import LinearRegression
regression = LinearRegression()
regression.fit(X_train, y_train)
# Predecir el conjunto de test
y_pred = regression.predict(X_test)
df = pd.DataFrame(y_pred)
#df.to_csv (r'/valohai/outputs/export_dataframe.csv', index = False, header=True)
print(y_pred)

# Visualizar los resultados de entrenamiento
plt.scatter(X_train, y_train, color = "red")
plt.plot(X_train, regression.predict(X_train), color = "blue")
plt.title("Sueldo vs Años de Experiencia (Conjunto de Entrenamiento)")
plt.xlabel("Años de Experiencia")
plt.ylabel("Sueldo (en $)")

save_path1 = valohai.outputs().path('myplot1.png')
plt.savefig(save_path1)

plt.show()
plt.close()

# Visualizar los resultados de test
plt.scatter(X_test, y_test, color = "red")
plt.plot(X_train, regression.predict(X_train), color = "blue")
plt.title("Sueldo vs Años de Experiencia (Conjunto de Testing)")
plt.xlabel("Años de Experiencia")
plt.ylabel("Sueldo (en $)")


save_path2 = valohai.outputs().path('myplot2.png')
plt.savefig(save_path2)

plt.show()
plt.close()


In [5]:
a= X_train.tolist()

In [7]:
type(a[0])

list

In [20]:
list(y_train)

[56642.0,
 66029.0,
 64445.0,
 61111.0,
 113812.0,
 91738.0,
 46205.0,
 121872.0,
 60150.0,
 39891.0,
 81363.0,
 93940.0,
 57189.0,
 54445.0,
 105582.0,
 43525.0,
 39343.0,
 98273.0,
 67938.0,
 56957.0]

In [ ]:
x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 8, 10]

data = list(zip(x, y))
print(data)

In [17]:
xtrain=pd.DataFrame(X_train,columns=["X_train"])
ytrain=pd.DataFrame(y_train,columns=["y_train"])

In [18]:
traincsv = pd.concat([xtrain, ytrain])

In [16]:
traincsv

X_train   y_train
0       2.9       NaN
1       5.1       NaN
2       3.2       NaN
3       4.5       NaN
4       8.2       NaN
5       6.8       NaN
6       1.3       NaN
7      10.5       NaN
8       3.0       NaN
9       2.2       NaN
10      5.9       NaN
11      6.0       NaN
12      3.7       NaN
13      3.2       NaN
14      9.0       NaN
15      2.0       NaN
16      1.1       NaN
17      7.1       NaN
18      4.9       NaN
19      4.0       NaN
0       NaN   56642.0
1       NaN   66029.0
2       NaN   64445.0
3       NaN   61111.0
4       NaN  113812.0
5       NaN   91738.0
6       NaN   46205.0
7       NaN  121872.0
8       NaN   60150.0
9       NaN   39891.0
10      NaN   81363.0
11      NaN   93940.0
12      NaN   57189.0
13      NaN   54445.0
14      NaN  105582.0
15      NaN   43525.0
16      NaN   39343.0
17      NaN   98273.0
18      NaN   67938.0
19      NaN   56957.0

In [6]:
trainlist =list(zip(X_train,y_train))
train = pd.DataFrame(trainlist,columns=["X_train","y_train"])
#df.to_csv (r'/valohai/outputs/export_dataframe.csv', index = False, header=True)
train.to_csv (r'train_dataframe.csv', index = False, header=True)

In [8]:
trainlist

[(array([2.9]), 56642.0),
 (array([5.1]), 66029.0),
 (array([3.2]), 64445.0),
 (array([4.5]), 61111.0),
 (array([8.2]), 113812.0),
 (array([6.8]), 91738.0),
 (array([1.3]), 46205.0),
 (array([10.5]), 121872.0),
 (array([3.]), 60150.0),
 (array([2.2]), 39891.0),
 (array([5.9]), 81363.0),
 (array([6.]), 93940.0),
 (array([3.7]), 57189.0),
 (array([3.2]), 54445.0),
 (array([9.]), 105582.0),
 (array([2.]), 43525.0),
 (array([1.1]), 39343.0),
 (array([7.1]), 98273.0),
 (array([4.9]), 67938.0),
 (array([4.]), 56957.0)]

In [6]:
train

Empty DataFrame
Columns: [X_train, y_train]
Index: []

In [10]:
train = pd.DataFrame(columns = ['X_train', 'y_train'], X_train, y_train)
train

SyntaxError: positional argument follows keyword argument (<ipython-input-10-a9a010661e27>, line 1)

In [12]:
test= pd.DataFrame(X_test, y_test)
test

0
37731.0    1.5
122391.0  10.3
57081.0    4.1
63218.0    3.9
116969.0   9.5
109431.0   8.7
112635.0   9.6
55794.0    4.0
83088.0    5.3
101302.0   7.9

0
56642.0    2.9
66029.0    5.1
64445.0    3.2
61111.0    4.5
113812.0   8.2
91738.0    6.8
46205.0    1.3
121872.0  10.5
60150.0    3.0
39891.0    2.2
81363.0    5.9
93940.0    6.0
57189.0    3.7
54445.0    3.2
105582.0   9.0
43525.0    2.0
39343.0    1.1
98273.0    7.1
67938.0    4.9
56957.0    4.0

In [67]:
b

0
37731.0    1.5
122391.0  10.3
57081.0    4.1
63218.0    3.9
116969.0   9.5
109431.0   8.7
112635.0   9.6
55794.0    4.0
83088.0    5.3
101302.0   7.9

In [62]:
 pd.DataFrame(y_train)


0
0    56642.0
1    66029.0
2    64445.0
3    61111.0
4   113812.0
5    91738.0
6    46205.0
7   121872.0
8    60150.0
9    39891.0
10   81363.0
11   93940.0
12   57189.0
13   54445.0
14  105582.0
15   43525.0
16   39343.0
17   98273.0
18   67938.0
19   56957.0

In [41]:

df = pd.DataFrame(a)



                                                   0
0  [[2.9], [5.1], [3.2], [4.5], [8.2], [6.8], [1....
1  [[1.5], [10.3], [4.1], [3.9], [9.5], [8.7], [9...
2  [56642.0, 66029.0, 64445.0, 61111.0, 113812.0,...
3  [37731.0, 122391.0, 57081.0, 63218.0, 116969.0...


C:\Users\chitay.j103576\anaconda3\envs\ambiente_alliedglobal\lib\site-packages\pandas\core\internals\construction.py:309: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  values = np.array([convert(v) for v in values])


In [36]:
import pandas as pd
import numpy as np
lst = [["Jay",12,"BBA"],["Jack",15,"BSc"]]
df = pd.DataFrame(lst, columns = ['Name','Age','Course'])
len(df)

2

In [37]:
df

Name  Age Course
0   Jay   12    BBA
1  Jack   15    BSc

In [19]:
X_train.shape

(20, 1)

In [25]:
X_train

array([[ 2.9],
       [ 5.1],
       [ 3.2],
       [ 4.5],
       [ 8.2],
       [ 6.8],
       [ 1.3],
       [10.5],
       [ 3. ],
       [ 2.2],
       [ 5.9],
       [ 6. ],
       [ 3.7],
       [ 3.2],
       [ 9. ],
       [ 2. ],
       [ 1.1],
       [ 7.1],
       [ 4.9],
       [ 4. ]])

In [20]:
y_train.shape

(20,)

In [26]:
y_train

array([ 56642.,  66029.,  64445.,  61111., 113812.,  91738.,  46205.,
       121872.,  60150.,  39891.,  81363.,  93940.,  57189.,  54445.,
       105582.,  43525.,  39343.,  98273.,  67938.,  56957.])

In [22]:
X_test.shape

(10, 1)

In [23]:
X_test

array([[ 1.5],
       [10.3],
       [ 4.1],
       [ 3.9],
       [ 9.5],
       [ 8.7],
       [ 9.6],
       [ 4. ],
       [ 5.3],
       [ 7.9]])

In [21]:
y_test.shape 

(10,)

In [24]:
y_test

array([ 37731., 122391.,  57081.,  63218., 116969., 109431., 112635.,
        55794.,  83088., 101302.])